APP_OPTIM := debug
APP_PLATFORM := android-14
APP_CPPFLAGS += -std=c++11
NDK_TOOLCHAIN_VERSION=4.8
APP_STL=gnustl_shared
APP_CPPFLAGS += -g
APP_CPPFLAGS += -frtti
APP_CPPFLAGS += -fexceptions
APP_CPPFLAGS += -DANDROID -DASIO_STANDALONE -D__GXX_EXPERIMENTAL_CXX0X__
APP_ABI := armeabi-v7a x86
