/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_init
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_destroy
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_getState
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    getCredentials
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSSessionCredentials;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_getCredentials
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    getCredentialsProvider
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/providers/CSSessionCredentialsProviderAdapter;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_getCredentialsProvider
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    setCredentialsProvider
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/providers/CSSessionCredentialsProviderAdapter;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_setCredentialsProvider
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    getConfig
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSSessionConfig;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_getConfig
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    setConfig
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSSessionConfig;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_setConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    getCurrentUserId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_getCurrentUserId
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    hasCriticalTasks
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_hasCriticalTasks
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    getInstance
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSSession;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_getInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    login
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSUser;Ljava/lang/String;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_login
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    logout
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_logout
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    startSync
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_startSync
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    stopSync
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_stopSync
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    suspend
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_suspend
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_resume
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    addListener
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/listeners/CSListenerAdapter;)Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_addListener
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession
 * Method:    removeListener
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/listeners/CSListenerAdapter;)Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSession_removeListener
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
