/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer
 * Method:    getAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer_getAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer
 * Method:    setAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer_setAddress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer
 * Method:    getPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer_getPort
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer
 * Method:    setPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer_setPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer
 * Method:    getCSSessionConfigJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSServer_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
