/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
 * Method:    getPublicKey
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys_getPublicKey(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
 * Method:    setPublicKey
 * Signature: (Ljava/lang/String;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys_setPublicKey(
		JNIEnv *, jobject, jstring);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
 * Method:    getPrivateKey
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys_getPrivateKey(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
 * Method:    setPrivateKey
 * Signature: (Ljava/lang/String;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys_setPrivateKey(
		JNIEnv *, jobject, jstring);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
 * Method:    getPrivateKeySalt
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys_getPrivateKeySalt(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
 * Method:    setPrivateKeySalt
 * Signature: (Ljava/lang/String;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys_setPrivateKeySalt(
		JNIEnv *, jobject, jstring);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
 * Method:    getCSSessionConfigJNI
 * Signature: ()J
 */JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys_getPtrJNI(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys
 * Method:    destroy
 * Signature: ()V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys_destroy(
		JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

class com_simplexsolutionsinc_coresignkernelwrapper_session_CSUserKeys {
};
#endif

