/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    getDeviceCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_getDeviceCode
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    setDeviceCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_setDeviceCode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    getDeviceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_getDeviceName
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    setDeviceName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_setDeviceName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    getTempStoragePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_getTempStoragePath
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    setTempStoragePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_setTempStoragePath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    getPermanentStoragePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_getPermanentStoragePath
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    setPermanentStoragePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_setPermanentStoragePath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    getBundlePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_getBundlePath
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    setBundlePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_setBundlePath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    getCSSessionConfigJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_getCSSessionConfigJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionConfig_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
