/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser
 * Method:    getUserID
 * Signature: ()J
 */JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser_getUserID(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser
 * Method:    setUserID
 * Signature: (J)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser_setUserID(
		JNIEnv *, jobject, jlong);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser
 * Method:    getKeys
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSUserKeys;
 */JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser_getKeys(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser
 * Method:    setKeys
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSUserKeys;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser_setKeys(
		JNIEnv *, jobject, jobject);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser
 * Method:    getPtrJNI
 * Signature: ()J
 */JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser_getPtrJNI(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser
 * Method:    destroy
 * Signature: ()V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser_destroy(
		JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

class com_simplexsolutionsinc_coresignkernelwrapper_session_CSUser {
};
#endif

