/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    getRpcSession
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_getRpcSession(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    setRpcSession
 * Signature: (Ljava/lang/String;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_setRpcSession(
		JNIEnv *, jobject, jstring);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    getEventSession
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_getEventSession(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    setEventSession
 * Signature: (Ljava/lang/String;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_setEventSession(
		JNIEnv *, jobject, jstring);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    getRpcServers
 * Signature: ()[Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSServer;
 */JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_getRpcServers(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    setRpcServerc
 * Signature: ([Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSServer;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_setRpcServers(
		JNIEnv *, jobject, jobjectArray);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    getEventServers
 * Signature: ()[Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSServer;
 */JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_getEventServers(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    setEventServerc
 * Signature: ([Lcom/simplexsolutionsinc/coresignkernelwrapper/session/CSServer;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_setEventServers(
		JNIEnv *, jobject, jobjectArray);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    getCSCredentialsJNI
 * Signature: ()J
 */JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_getCSCredentialsJNI(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials
 * Method:    destroy
 * Signature: ()V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials_destroy(
		JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

namespace std {

class com_simplexsolutionsinc_coresignkernelwrapper_session_CSSessionCredentials {
};

} /* namespace std */
#endif

