/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateResultEvent */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateResultEvent
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateResultEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateResultEvent
 * Method:    getResult
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateResultEvent_getResult
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
