/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSEvent */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSEvent
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSEvent
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSEvent_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSEvent
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSEvent_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSEvent
 * Method:    getEventType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSEvent_getEventType
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
