/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListenerAdapter */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListenerAdapter
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListenerAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListenerAdapter
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListenerAdapter_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListenerAdapter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListenerAdapter_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
