/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSBroadcaster */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSBroadcaster
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSBroadcaster
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSBroadcaster
 * Method:    addListener
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/listeners/CSListenerAdapter;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSBroadcaster_addListener(
		JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSBroadcaster
 * Method:    removeListener
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/listeners/CSListenerAdapter;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSBroadcaster_removeListener(
		JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif

class com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSBroadcaster {
};
#endif

