/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListener */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListener
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
