/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateEvent */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateEvent
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateEvent
 * Method:    getTemplateID
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateID;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateEvent_getTemplateID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
