/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateProgressEvent */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateProgressEvent
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateProgressEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateProgressEvent
 * Method:    getProgress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_listeners_CSTemplateProgressEvent_getProgress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
