/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_SIGNATURE
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_SIGNATURE 0L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_INITIALS
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_INITIALS 1L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_FREEPAINT
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_FREEPAINT 2L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_TEXT
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_TEXT 3L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_DATE
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_DATE 4L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_CHECKBOX
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_CHECKBOX 5L
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    getAnnotationType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_getAnnotationType
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    getID
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/annotations/CSAnnotationID;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_getID
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    getFrame
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_getFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    setFrame
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_setFrame
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    isPlaceholder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_isPlaceholder
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    getOwner
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_getOwner
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    setOwner
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_setOwner
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    canUndo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_canUndo
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    canRedo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_canRedo
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    undo
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)I
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_undo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    redo
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)I
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_redo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    isEditable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_isEditable
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation
 * Method:    isContentEditable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotation_isContentEditable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
