/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    canUndo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_canUndo
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    canRedo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_canRedo
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    getAnnotationIDsForPage
 * Signature: (ILcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)[Lcom/simplexsolutionsinc/coresignkernelwrapper/annotations/CSAnnotationID;
 */
JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_getAnnotationIDsForPage
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    getPlaceholderIDsForUser
 * Signature: (JZ)[Lcom/simplexsolutionsinc/coresignkernelwrapper/annotations/CSAnnotationID;
 */
JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_getPlaceholderIDsForUser
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    getPageForAnnotation
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/annotations/CSAnnotationID;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_getPageForAnnotation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    getAnnotation
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSID;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)Lcom/simplexsolutionsinc/coresignkernelwrapper/annotations/CSAnnotation;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_getAnnotation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    createAnnotationOnPage
 * Signature: (IILcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)Lcom/simplexsolutionsinc/coresignkernelwrapper/annotations/CSAnnotationID;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_createAnnotationOnPage
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    removeAnnotation
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/annotations/CSAnnotationID;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_removeAnnotation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    undo
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_undo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore
 * Method:    redo
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationStore_redo
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
