/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_SIGNATURE
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_SIGNATURE 0L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_INITIALS
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_INITIALS 1L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_FREEPAINT
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_FREEPAINT 2L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_TEXT
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_TEXT 3L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_DATE
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_DATE 4L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_CHECKBOX
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_CHECKBOX 5L
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation
 * Method:    getDate
 * Signature: ()I
 */JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_getDate(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation
 * Method:    setDate
 * Signature: (I)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_setDate(
		JNIEnv *, jobject, jlong);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation
 * Method:    getFont
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_getFont(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation
 * Method:    setFont
 * Signature: (Ljava/lang/String;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_setFont(
		JNIEnv *, jobject, jstring);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation
 * Method:    getColor
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/CSColor;
 */JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_getColor(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation
 * Method:    setColor
 * Signature: ([B)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation_setColor(
		JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif

class com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSDateAnnotation {
};
#endif

