/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationID */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationID
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationID
 * Method:    getPtrJNI
 * Signature: ()J
 */JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationID_getPtrJNI(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationID
 * Method:    destroy
 * Signature: ()V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationID_destroy(
		JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

class com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSAnnotationID {
};
#endif

