/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_SIGNATURE
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_SIGNATURE 0L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_INITIALS
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_INITIALS 1L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_FREEPAINT
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_FREEPAINT 2L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_TEXT
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_TEXT 3L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_DATE
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_DATE 4L
#undef com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_CHECKBOX
#define com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_CHECKBOX 5L
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_getText(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation
 * Method:    setText
 * Signature: (Ljava/lang/String;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_setText(
		JNIEnv *, jobject, jstring);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation
 * Method:    getFont
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_getFont(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation
 * Method:    setFont
 * Signature: (Ljava/lang/String;)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_setFont(
		JNIEnv *, jobject, jstring);
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation
 * Method:    getColor
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/CSColor;
 */JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_getColor(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation
 * Method:    setColor
 * Signature: ([B)V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation_setColor(
		JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif

class com_simplexsolutionsinc_coresignkernelwrapper_annotations_CSTextAnnotation {
};
#endif

