/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateFilter */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateFilter
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateFilter
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateFilter_getType
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
