/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_templates_CSByAuthorTemplateFilter */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSByAuthorTemplateFilter
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSByAuthorTemplateFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSByAuthorTemplateFilter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSByAuthorTemplateFilter_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSByAuthorTemplateFilter
 * Method:    getAuthor
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateAuthor;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSByAuthorTemplateFilter_getAuthor
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSByAuthorTemplateFilter
 * Method:    init
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateAuthor;)J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSByAuthorTemplateFilter_init
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
