/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_templates_CSStringQueryTemplateFilter */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSStringQueryTemplateFilter
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSStringQueryTemplateFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSStringQueryTemplateFilter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSStringQueryTemplateFilter_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSStringQueryTemplateFilter
 * Method:    getQuery
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSStringQueryTemplateFilter_getQuery
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSStringQueryTemplateFilter
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSStringQueryTemplateFilter_init
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
