/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
 * Method:    getTemplateAuthors
 * Signature: ()[Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateAuthor;
 */
JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager_getTemplateAuthors
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
 * Method:    getTemplateIDs
 * Signature: ()[Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateID;
 */
JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager_getTemplateIDs__
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
 * Method:    getTemplateIDs
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateFilter;)[Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateID;
 */
JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager_getTemplateIDs__Lcom_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateFilter_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
 * Method:    getTemplate
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateID;)Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplate;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager_getTemplate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
 * Method:    cleanCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager_cleanCache
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
 * Method:    addListener
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/listeners/CSListenerAdapter;)Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager_addListener
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager
 * Method:    removeListener
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/listeners/CSListenerAdapter;)Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplateManager_removeListener
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
