/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_templates_CSCompositeTemplateFilter */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSCompositeTemplateFilter
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSCompositeTemplateFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSCompositeTemplateFilter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSCompositeTemplateFilter_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSCompositeTemplateFilter
 * Method:    getFilters
 * Signature: ()[Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateFilter;
 */
JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSCompositeTemplateFilter_getFilters
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSCompositeTemplateFilter
 * Method:    init
 * Signature: ([Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateFilter;)J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSCompositeTemplateFilter_init
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
