/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    getId
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateID;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_getId
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    getTemplateAuthor
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/templates/CSTemplateAuthor;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_getTemplateAuthor
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    getCreationDateMilis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_getCreationDateMilis
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    getUpdateDateMilis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_getUpdateDateMilis
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    getFetchingProgress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_getFetchingProgress
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    getPreviewPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_getPreviewPath
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    fetch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_fetch
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate
 * Method:    fetchPreview
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_templates_CSTemplate_fetchPreview
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
