/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_empty
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_empty 0L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_ByName
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_ByName 1L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_BySigner
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_BySigner 2L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_Whoever
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_Whoever 0L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_Me
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_Me 1L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_Partner
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_Partner 2L
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter
 * Method:    init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter
 * Method:    getSignerType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSBySignerDocumentFilter_getSignerType
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
