/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    init
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentManager;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_init
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    getDocumentsIds
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)[Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;
 */
JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_getDocumentsIds__Lcom_simplexsolutionsinc_coresignkernelwrapper_CSResult_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    getDocumentsIds
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentFilter;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)[Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;
 */
JNIEXPORT jobjectArray JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_getDocumentsIds__Lcom_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentFilter_2Lcom_simplexsolutionsinc_coresignkernelwrapper_CSResult_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    getDocument
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocument;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_getDocument
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    createDocument
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSPDF;ILcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_createDocument
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    cloneDocument
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_cloneDocument
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    removeDocument
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_removeDocument
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    saveDocument
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocument;Lcom/simplexsolutionsinc/coresignkernelwrapper/providers/CSDocumentPreviewProvider;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_saveDocument
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    finishSigningDocument
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_finishSigningDocument
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    requestShareIdForDocument
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_requestShareIdForDocument
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    requestDocumentForShareId
 * Signature: (Ljava/lang/String;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_requestDocumentForShareId
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    cleanCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_cleanCache
  (JNIEnv *, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    addListener
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/listeners/CSListenerAdapter;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_addListener
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager
 * Method:    removeListener
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/listeners/CSListenerAdapter;Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentManager_removeListener
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
