/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent
 * Method:    getPDF
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSPDF;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent_getPDF
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent
 * Method:    getNumberOfPages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent_getNumberOfPages
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent
 * Method:    getAnnotationStore
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/annotations/CSAnnotationStore;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentContent_getAnnotationStore
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
