/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter_empty
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter_empty 0L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter_ByName
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter_ByName 1L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter_BySigner
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter_BySigner 2L
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter
 * Method:    getDocumentName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSByNameDocumentFilter_getDocumentName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
