/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentID */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentID
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentID
 * Method:    getPtrJNI
 * Signature: ()J
 */JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentID_getPtrJNI(
		JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentID
 * Method:    destroy
 * Signature: ()V
 */JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentID_destroy(
		JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

class com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentID {
};
#endif

