/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
#ifdef __cplusplus
extern "C" {
#endif
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_Prepare
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_Prepare 0L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_Fill
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_Fill 1L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_Complete
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_Complete 2L
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getId
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentID;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getId
 (JNIEnv *, jobject);

/*
* Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
* Method:    getName
* Signature: ()Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getName
 (JNIEnv *, jobject);

/*
* Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
* Method:    getAuthor
* Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumenParticipant;
*/
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getAuthor
 (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getAuthor
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumenParticipant;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getAuthor
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getNote
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getNote
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    setNote
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_setNote
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getState
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getCreationDateMilis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getCreationDateMilis
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getUpdateDateMilis
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getUpdateDateMilis
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getContent
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentContent;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getContent
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getParticipantManager
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/documents/CSDocumentParticipantManager;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getParticipantManager
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getNumberOfPages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getNumberOfPages
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getContentFetchingProgress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getContentFetchingProgress
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    getPreviewPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_getPreviewPath
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    fetchPreview
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_fetchPreview
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument
 * Method:    fetchContent
 * Signature: (Lcom/simplexsolutionsinc/coresignkernelwrapper/CSResult;)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocument_fetchContent
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
