/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
#ifdef __cplusplus
extern "C" {
#endif
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Uknown_Participant
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Uknown_Participant 0L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Waiting
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Waiting 1L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Signing
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Signing 2L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Sent
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Sent 3L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Unknown_Role
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Unknown_Role 0L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Author
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Author 1L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Observer
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Observer 2L
#undef com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Signer
#define com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_Signer 3L
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    getId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_getId
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    setId
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_setId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    getStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_getStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    setStatus
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_setStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    getRole
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_getRole
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    setRole
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_setRole
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    getColor
 * Signature: ()Lcom/simplexsolutionsinc/coresignkernelwrapper/CSColor;
 */
JNIEXPORT jobject JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_getColor
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant
 * Method:    setColor
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_documents_CSDocumentParticipant_setColor
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
