/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewAdapter */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewAdapter
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewAdapter
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewAdapter_init
  (JNIEnv *, jclass, jclass);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewAdapter
 * Method:    getPtrJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewAdapter_getPtrJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewAdapter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewAdapter_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
