/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_providers_CSSessionCredentialsProvider */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_providers_CSSessionCredentialsProvider
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_providers_CSSessionCredentialsProvider
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
