/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewProvider */

#ifndef _Included_com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewProvider
#define _Included_com_simplexsolutionsinc_coresignkernelwrapper_providers_CSDocumentPreviewProvider
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
